#+TITLE: デジタル版しおりアプリの開発
#+ID: 37022463
#+AUTHOR: 西谷研究室　山本果音
#+LANGUAGE: jp
#+OPTIONS: ^:{}
#+LATEX_HEADER:\renewcommand{\bibname}
#+LATEX_HEADER: \documentclass{jsarticle}


* 序論

修学旅行などのイベントでは, 参加者に対して事前にしおりが配布されることが多い.
しおりは旅程の把握や所持品の確認, 集合時間の共有などを目的とした重要な情報媒体であり, 旅行の準備や当日の行動において欠かせない役割を果たしている.
近年では,スマートフォンの普及により, 紙媒体に代わってWebサービスを活用した旅行データの閲覧・共有の
ニーズが高まっており, 「旅しお」[1]のようなWebアプリも登場している.
しかし, これらのサービスにはいくつかの課題が存在する.

1つ目は, 旅行名や説明文に対するキーワード検索機能が存在しないため, ユーザーはスクロール操作によって目的のしおりを探す必要がある点である.

2つ目は, 地図表示機能がないため, 目的地の位置関係や全体像を視覚的に理解することが難しく, 利用者は外部ツールや手作業で補完しなければならない.

3つ目は, 移動時間の自動算出機能が存在しないため, 各目的地間の所要時間をユーザー自身が都度手動で調べる必要がある点である. これにより, 旅行全体のスケジュールを立てる際に手間がかかり, 計画の精度や効率性が低下する可能性がある.

これらの課題は, 旅行計画の際にユーザーにとって大きな障壁となっており, データの整理や視覚的な理解の低下が考えられる.
そこで本研究では, 視覚的な理解と効率的に旅行計画を行える「デジタル版しおり」として機能する旅行アプリの開発を目指す.

* 開発手法
本研究では, 限られた開発期間内で効率的に成果を上げるために, 機能ごとに優先順位を設定し, それぞれについて計画・設計・実装・テストの工程を小刻みに繰り返すアジャイル開発手法を採用した.  

開発環境としてはDjango[2]を選定した.
Djangoとは, PythonベースのWebフレームワークのことである. 


*  結果

本アプリでの旅行詳細共有までの流れとして, まず新規アカウント登録後にログイン画面へ遷移し, 旅行一覧画面で旅行を作成する. その後, 旅行詳細画面において地図表示, 観光地登録, 移動時間の自動算出, 訪問順序の入れ替え, タブ切り替えなどの旅程編集を行う. 

図1に示したように, 左パネルで示す全旅程画面で, 個別の日程を選択すると, 右パネルのように遷移する. これにより, 個別日の旅程のみを詳しく確認することや, 行き先を変更・追加するなど柔軟な操作が可能となる.

#+CAPTION: 日程タブ選択時の旅行詳細画面の変化.
#+attr_latex: :width 8cm
file:./figs/trip.png

旅行詳細が完成後, 図2に示したようにパスワードと有効期限を設定した生成したリンクを家族や友人に共有することで, 受け手は旅行情報を閲覧できる. 
また, 旅行作成者が内容を変更した場合でも, リンクの有効期限内であれば常に最新の情報が反映されるようになっている. 

#+CAPTION: 旅行詳細共有までの流れ.
#+attr_latex: :width 6cm
file:./figs/share_1.png

さらに, 旅行準備を効率的に進められるよう, チェックリスト機能を実装した.
ユーザーが日常的に持参する物をデフォルトのチェックリストとして登録できるようにし, 各旅行に自動で反映される仕組みとした. 
また, 旅行先や季節に応じて必要な持ち物が異なることを考慮し, 旅行ごとにチェックリストを自由に編集可能な設計とした. 
これにより, 忘れ物対策や準備作業の整理が容易となる.

*  まとめ
本アプリではDjango を用いて地図表示, 移動時間の自動算出, 共有などに加え,チェックリスト機能も備えた.
これにより，「旅しお」よりも旅行計画と準備を効率的に進められる旅行支援アプリとなった.

\small\setlength\baselineskip{10pt}
\begin{thebibliography}{9}

\bibitem{旅しお} 旅しお,\url{https://tabisio.com/},(2025/09/05 accessed).
\bibitem{Django-site}Django,\url{https://www.djangoproject.com/},(2025/09/05 accessed).
\end{thebibliography}
